spring:
  # druid
  datasource:
    name: dev-db
    druid:
      url: jdbc:mysql://localhost:3307/heart?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
  # mail
  mail:
    host: smtp.qq.com
    username: illure_work@foxmail.com
    password: hpuolkaqilpodfgh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
           enable: true
           required: true
  # activemq
  activemq:
    broker-url: tcp://localhost:61616
    pool:
      enabled: false
  # redis
  redis:
    node: localhost:6379
    auth: root