spring:
  # druid
  datasource:
    name: dev-db
    druid:
      url: jdbc:mysql://localhost:3306/heart?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root